# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d53c744465403c86069852d9e6a909561c1611de9a0392a5ac5689602e6f25fff6b6ff7d1b63ca996151f3f385b400462ee976b5f3c5831697d43d61f61cbb1f

test:
  secret_key_base: 78a17e31051bb8e7ee7f9c5babe4dc9a9e5769acfc84256413c195713c6d1dc52629827a1b480e07323e85d176ee2742a3322177a2035602d5ef2e79a59146f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
